### ISSUE TITLE
Need the Flex Sensor

### ISSUE THREAD

**Issue by djiesr** [arsenicks/pyhydroquebec-hass-addons#10]
It's work great. 
It need to wait a cycle to be update after restart, but it's not a problem.
For the Hydro-Quebec Flex: https://github.com/titilambert/pyhydroquebec/issues/61
Can you add it?

**Comment by arsenicks** [comment]
Hi, I can't really add features. I mean it *could* be done but it will be ugly and hard to maintain.. I'm only using the pyhydroquebec python script installed from pypi.. If the maintainer of pyhydroquebec doesn't show up someone will have to fork the repo and maintain it.

Regarding this add-on I just got subscribed to Hilo last week. So I'm not using pyhydroquebec anymore, I'll try to keep fixing bugs and help but if someone want to step up and fork this one too that would surely give everyone a better experience!

**Comment by marc25v** [comment]
Hey Arsenicks!

Thanks for letting us know.  Do you think you could use the following repo instead: https://github.com/tech165/pyhydroquebec

Seems to be live with the Flex Sensor.

Thanks again
