### ISSUE TITLE
Consolidation of hydro related project

### ISSUE THREAD

**Issue by zepiaf** [arsenicks/pyhydroquebec-hass-addons#12]
Hello, @titilambert, @mdallaire and myself  are working on a revamp of pyhydroquebec.

We would very much like to talk to you on what kind of consolidation we could make and work together rather than separately.

If you're interested would you like to join us on discord to discuss this:

https://discord.gg/BTPDntfaXH

For reference the new project is on gitlab : https://gitlab.com/hydroqc/hydroqc

**Comment by arsenicks** [comment]
Sure, I just joined.
