### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by nips1900** [arsenicks/pyhydroquebec-hass-addons#6]
Hi,

Do you think there is a way to pull the history?

Do you think there is a way to pull the hourly data?

kind regards,

Laurent

**Comment by arsenicks** [comment]
Hi!

This addon is just a Dockerfile used to build the container running the addon, it runs the https://github.com/titilambert/pyhydroquebec/ code pulled from the PyPi repository so I don't have any easy and clean way to add features or bugfix.

To awnser your questions, yes and yes but this should be done upstream, I just install pyhydroquebec in the image, I don't modify the code or have any affiliation with titilambert so we have to wait for him or someone else to take the lead..

**Comment by MatheGeek** [comment]
Hi,  
I think the best way to get your history is to create some sensors that will comply with the requirements of the HA Energy Dashboard. 
I've detailed how I did it  there  :  https://github.com/MatheGeek/pyhydroquebec-integration-to-HA-Energy-Dashboard
I'm very new to Github,  I hope it helps.
