### ISSUE TITLE
Winter Credit Messaging

### ISSUE THREAD

**Issue by marc25v** [arsenicks/pyhydroquebec-hass-addons#7]
Great work first of all!  Works like a charm.  Would it be possible to add the following MQTT message regarding the winter credit notification:
https://github.com/titilambert/pyhydroquebec/pull/63/files

This would allow us to add some automation to reduce consumption during the peak periods.

**Comment by arsenicks** [comment]
Thanks! There's some work needed to cleanup the use of files vs config entry, I will get back to it soon.

Regarding your request, unfortunately I can't. This addon is just a Dockerfile used to build the container running the addon, it runs the https://github.com/titilambert/pyhydroquebec/ code pulled from the PyPi repository so I don't have any easy and clean way to add features or bugfix. I mean we could clone the repo and patch the files but I don't want to maintain that, it never age well..

Someone will have to fork the original repo and take the lead if the maintainer doesn't get back to life soon.. There's a lot of good PR submitted and the last commits date back in january.
